### ISSUE TITLE
For Install my this Pluggin :scream:

### ISSUE THREAD

**Issue by oguhpereira** [oguhpereira/Dracula-WordPress#2]
# For install this pluggin. :scream:

1. Add the folder Dracula-custom-admin-color-schemes in your WordPress folder ./wp-content/pluggin
2. Open your dashbord
3. You have go to pluggin tab.
4. In your pluggin tab active Dracula theme Pluggin.

**Comment by allamiro** [comment]
So does this theme generate pages with Dracula theme colors what if you want to add like a tutorial that shows Linux bash command line does it show the same color?

**Comment by oguhpereira** [comment]
This plugin change the Colors of WordPress Dashboard.  It doesn't generate pages
